---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      containers:
        - name: redis
          image: redis:7.2
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
          command: ["redis-server"]
          args: ["/etc/redis.conf"]
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          volumeMounts:
            - name: redis-config
              mountPath: /etc/
              subPath: redis.conf
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-config
          emptyDir: {}
        - name: redis-config-map
          configMap:
            name: redis
      initContainers:
        - name: config
          image: redis:7.2
          command: ["bash", "-c"]
          args:
            - cp /mnt/config-map/master.conf /etc/redis.conf
          volumeMounts:
            - name: redis-config
              mountPath: /etc
              subPath: redis.conf
            - name: redis-config-map
              mountPath: /mnt/config-map/
